spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javaseven
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
server:
  error:
    include-message: always